dataset: suzakuteam/omni_math_1000

id_col: null
question_col: problem
answer_col: answer
thinking_col: solution

provider: vllm

base_url: http://localhost:8010/v1

# 最後に / があるとエラーになるので注意！
model: /home/Competition2025/P12/shareP12/models/Qwen3-32B

max_completion_tokens: 16384 # 32768
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 2400

# 全件やりたいときはnull
max_samples: null

judge: /home/Competition2025/P12/shareP12/models/Qwen3-235B-A22B-FP8/
