dataset: toloka/u-math # KbsdJames/Omni-MATH

id_col: uuid
question_col: problem_statement
answer_col: golden_answer
thinking_col: null

provider: vllm

base_url: http://localhost:8010/v1

# 最後に / があるとエラーになるので注意！
model: /home/Competition2025/P12/shareP12/models/Qwen3-32B-FP8

max_completion_tokens: 16384 # 32768
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 2400

# 全件やりたいときはnull
max_samples: null

judge: /home/Competition2025/P12/shareP12/models/Qwen3-235B-A22B-FP8/
