dataset: toloka/u-math # KbsdJames/Omni-MATH

id_col: uuid
question_col: question
answer_col: golden_answer
thinking_col: problem_statement

provider: vllm # [vllm]

base_url: http://localhost:8000/v1

model: /home/Competition2025/P12/shareP12/models/Qwen3-32B # Qwen/Qwen3-32B
max_completion_tokens: 32768
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 2400

# 全件やりたいときはコメントアウト
max_samples: null

judge: /home/Competition2025/P12/shareP12/models/Qwen3-235B-A22B-FP8/
